besu:
  additionalFlags: ""
  containerTag: hyperledger/besu:23.1.2
  jvmHeapSize: "0"
  maxBackLayers: "512"
  maxPeers: "25"
bitflyNodeMetrics:
  bitflyEndpoint: https://beaconcha.in/api/v1/client/metrics
  bitflyMachineName: Stadernode
  bitflySecret: ""
consensusCommon:
  apiPort: "5052"
  checkpointSyncUrl: ""
  doppelgangerDetection: "true"
  graffiti: StaderLabs
  openApiPort: "false"
  p2pPort: "9001"
executionCommon:
  enginePort: "8551"
  ethstatsLabel: ""
  ethstatsLogin: ""
  httpPort: "8545"
  openRpcPorts: "false"
  p2pPort: "30303"
  wsPort: "8546"
exporter:
  additionalFlags: ""
  containerTag: prom/node-exporter:v1.5.0
  enableRootFs: "false"
externalExecution:
  httpUrl: ""
  wsUrl: ""
externalLighthouse:
  additionalVcFlags: ""
  containerTag: sigp/lighthouse:v3.5.1-modern
  doppelgangerDetection: "true"
  graffiti: StaderLabs
  httpUrl: ""
externalNimbus:
  additionalVcFlags: ""
  containerTag: statusim/nimbus-validator-client:multiarch-v23.3.1
  doppelgangerDetection: "true"
  graffiti: StaderLabs
  httpUrl: ""
externalPrysm:
  additionalVcFlags: ""
  containerTag: staderdev/prysm:v3.2.2-rc.3
  doppelgangerDetection: "true"
  graffiti: StaderLabs
  httpUrl: ""
  jsonRpcUrl: ""
externalTeku:
  additionalVcFlags: ""
  containerTag: consensys/teku:23.3.1
  graffiti: StaderLabs
  httpUrl: ""
fallbackNormal:
  ccHttpUrl: ""
  ecHttpUrl: ""
fallbackPrysm:
  ccHttpUrl: ""
  ecHttpUrl: ""
  jsonRpcUrl: ""
geth:
  additionalFlags: ""
  cache: "4096"
  containerTag: ethereum/client-go:v1.11.4
  maxPeers: "25"
  usePebble: "false"
grafana:
  containerTag: grafana/grafana:9.3.1
  port: "3100"
lighthouse:
  additionalBnFlags: ""
  additionalVcFlags: ""
  containerTag: sigp/lighthouse:v3.5.1-modern
  maxPeers: "80"
mevBoost:
  additionalFlags: ""
  blocknativeEnabled: "false"
  bloxRouteEthicalEnabled: "false"
  bloxRouteMaxProfitEnabled: "false"
  bloxRouteRegulatedEnabled: "false"
  containerTag: flashbots/mev-boost:1.4.0
  edenEnabled: "false"
  enableRegulatedAllMev: "false"
  enableRegulatedNoSandwich: "false"
  enableUnregulatedAllMev: "false"
  enableUnregulatedNoSandwich: "false"
  externalUrl: ""
  flashbotsEnabled: "false"
  mode: external
  openRpcPort: "false"
  port: "18550"
  selectionMode: profile
  ultrasoundEnabled: "false"
native:
  ccHttpUrl: ""
  consensusClient: nimbus
  ecHttpUrl: ""
  validatorRestartCommand: ~/.stader/restart-vc.sh
  validatorStopCommand: ~/.stader/stop-validator.sh
nethermind:
  additionalFlags: ""
  additionalModules: ""
  additionalUrls: ""
  cache: "1024"
  containerTag: nethermind/nethermind:1.17.2
  maxPeers: "25"
  pruneMemSize: "1024"
nimbus:
  additionalBnFlags: ""
  additionalVcFlags: ""
  bnContainerTag: statusim/nimbus-eth2:multiarch-v23.3.1
  containerTag: statusim/nimbus-validator-client:multiarch-v23.3.1
  maxPeers: "100"
  pruningMode: archive
prometheus:
  additionalFlags: ""
  containerTag: prom/prometheus:v2.41.0
  openPort: "false"
  port: "9091"
prysm:
  additionalBnFlags: ""
  additionalVcFlags: ""
  bnContainerTag: staderdev/prysm:v3.2.2-rc.3
  maxPeers: "45"
  openRpcPort: "false"
  rpcPort: "5053"
  vcContainerTag: staderdev/prysm:v3.2.2-rc.3
root:
  bnMetricsPort: "9100"
  consensusClient: lighthouse
  consensusClientMode: local
  ecMetricsPort: "9105"
  enableBitflyNodeMetrics: "false"
  enableGuardianMetrics: "false"
  enableMetrics: "true"
  enableMevBoost: "true"
  executionClient: besu
  executionClientMode: local
  exporterMetricsPort: "9103"
  externalConsensusClient: lighthouse
  guardianMetricsPort: "9104"
  isNative: "false"
  nodeMetricsPort: "9102"
  reconnectDelay: 60s
  sdDir: ~/.stader
  useFallbackClients: "true"
  vcMetricsPort: "9101"
  version: v0.3.1-stage
stadernode:
  archiveECUrl: ""
  dataPath: ~/.stader/data
  manualMaxFee: "0"
  network: prater
  priorityFee: "2"
  projectName: stader
teku:
  additionalBnFlags: ""
  additionalVcFlags: ""
  archiveMode: "false"
  containerTag: consensys/teku:23.3.1
  jvmHeapSize: "0"
  maxPeers: "100"
